/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IProfitDistributorV2 } from "./IProfitDistributorV2";
export type { RWATokenV2 } from "./RWATokenV2";
