import mongoose from 'mongoose';
import Product from '../models/Product.model';
import Category from '../models/Category.model';
import dotenv from 'dotenv';

dotenv.config();

const categories = [
  { name: 'Electronics', slug: 'electronics', description: 'Electronic devices and gadgets', order: 1 },
  { name: 'Fashion', slug: 'fashion', description: 'Clothing and accessories', order: 2 },
  { name: 'Home & Garden', slug: 'home-garden', description: 'Home decor and garden items', order: 3 },
  { name: 'Sports & Outdoors', slug: 'sports-outdoors', description: 'Sports equipment and outdoor gear', order: 4 },
  { name: 'Jewelry & Watches', slug: 'jewelry-watches', description: 'Fine jewelry and luxury watches', order: 5 },
  { name: 'Collectibles & Art', slug: 'collectibles-art', description: 'Rare collectibles and artwork', order: 6 },
  { name: 'Real Estate', slug: 'real-estate', description: 'Properties and land', order: 7 },
  { name: 'Automotive', slug: 'automotive', description: 'Cars, motorcycles, and parts', order: 8 },
];

// Coin data for consistent pricing
const coinData = [
  {
    symbol: 'BTC',
    logo: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
    priceUSD: 43000,
  },
  {
    symbol: 'ETH',
    logo: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    priceUSD: 2300,
  },
  {
    symbol: 'USDT',
    logo: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
    priceUSD: 1,
  },
  {
    symbol: 'BNB',
    logo: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
    priceUSD: 320,
  },
  {
    symbol: 'XRP',
    logo: 'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png',
    priceUSD: 0.52,
  },
];

const realWorldProducts = [
  // Jewelry & Watches - High value items use BTC
  {
    title: 'Vintage Rolex Submariner Watch',
    description: 'Authentic vintage Rolex Submariner from 1960s. Fully serviced and authenticated. Comes with original box and papers.',
    category: 'jewelry-watches',
    images: ['https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600'],
    priceInCoins: 1.163,
    priceInUSD: 50000,
    coinSymbol: 'BTC',
    coinLogo: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
    condition: 'LIKE_NEW',
    quantity: 1,
    location: 'New York, USA',
    tags: ['luxury', 'vintage', 'rolex', 'watch'],
    sellerId: 'seed-seller-1',
    sellerName: 'Luxury Timepieces',
    rating: 4.9,
    reviews: 128,
  },
  {
    title: 'Cartier Love Bracelet',
    description: '18K yellow gold Cartier Love bracelet. Iconic design with screw motif. Includes original box and certificate.',
    category: 'jewelry-watches',
    images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600'],
    priceInCoins: 2.826,
    priceInUSD: 6500,
    coinSymbol: 'ETH',
    coinLogo: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    condition: 'NEW',
    quantity: 2,
    location: 'Paris, France',
    tags: ['cartier', 'bracelet', 'gold', 'luxury'],
    sellerId: 'seed-seller-1',
    sellerName: 'Luxury Timepieces',
    rating: 4.8,
    reviews: 95,
  },
  {
    title: 'Diamond Engagement Ring 2ct',
    description: 'Stunning 2 carat diamond engagement ring in platinum setting. GIA certified, excellent cut.',
    category: 'jewelry-watches',
    images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600'],
    priceInCoins: 0.395,
    priceInUSD: 17000,
    coinSymbol: 'BTC',
    coinLogo: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
    condition: 'NEW',
    quantity: 1,
    location: 'New York, USA',
    tags: ['diamond', 'engagement', 'ring', 'gia'],
    sellerId: 'seed-seller-1',
    sellerName: 'Luxury Timepieces',
    rating: 5.0,
    reviews: 67,
  },

  // Electronics - Mid-range items use ETH
  {
    title: 'MacBook Pro 16" M3 Max',
    description: 'Latest MacBook Pro with M3 Max chip, 64GB RAM, 2TB SSD. Perfect for professionals.',
    category: 'electronics',
    images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600'],
    priceInCoins: 1.304,
    priceInUSD: 3000,
    coinSymbol: 'ETH',
    coinLogo: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    condition: 'NEW',
    quantity: 10,
    location: 'Seattle, USA',
    tags: ['apple', 'laptop', 'macbook', 'professional'],
    sellerId: 'seed-seller-2',
    sellerName: 'Tech Store',
    rating: 4.7,
    reviews: 234,
  },
  {
    title: 'iPhone 15 Pro Max 1TB',
    description: 'Latest iPhone 15 Pro Max with 1TB storage. Natural Titanium color. Factory unlocked.',
    category: 'electronics',
    images: ['https://images.unsplash.com/photo-1592286927505-b0c2e0a83b6f?w=600'],
    priceInCoins: 0.65,
    priceInUSD: 1299,
    condition: 'NEW',
    quantity: 15,
    location: 'Cupertino, USA',
    tags: ['iphone', 'apple', 'smartphone', 'pro'],
    sellerId: 'seed-seller-2',
    sellerName: 'Tech Store',
  },
  {
    title: 'Sony A7R V Camera',
    description: 'Professional full-frame mirrorless camera with 61MP sensor. Includes 24-70mm lens.',
    category: 'electronics',
    images: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600'],
    priceInCoins: 2.0,
    priceInUSD: 4000,
    condition: 'NEW',
    quantity: 5,
    location: 'Tokyo, Japan',
    tags: ['camera', 'sony', 'photography', 'professional'],
    sellerId: 'seed-seller-2',
    sellerName: 'Tech Store',
  },
  {
    title: 'iPad Pro 12.9" M2',
    description: 'iPad Pro with M2 chip, 12.9" Liquid Retina XDR display, 512GB. Includes Magic Keyboard.',
    category: 'electronics',
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600'],
    priceInCoins: 0.85,
    priceInUSD: 1700,
    condition: 'NEW',
    quantity: 8,
    location: 'Seattle, USA',
    tags: ['ipad', 'apple', 'tablet', 'pro'],
    sellerId: 'seed-seller-2',
    sellerName: 'Tech Store',
  },
  {
    title: 'Samsung 85" QLED 8K TV',
    description: 'Samsung Neo QLED 8K smart TV with quantum HDR and object tracking sound.',
    category: 'electronics',
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600'],
    priceInCoins: 3.5,
    priceInUSD: 7000,
    condition: 'NEW',
    quantity: 3,
    location: 'Seoul, South Korea',
    tags: ['tv', 'samsung', '8k', 'qled'],
    sellerId: 'seed-seller-2',
    sellerName: 'Tech Store',
  },

  // Automotive
  {
    title: 'Tesla Model S P100D',
    description: 'Tesla Model S P100D with Ludicrous Mode. Low mileage, full self-driving capability.',
    category: 'automotive',
    images: ['https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=600'],
    priceInCoins: 40.0,
    priceInUSD: 80000,
    condition: 'GOOD',
    quantity: 1,
    location: 'San Francisco, USA',
    tags: ['tesla', 'electric', 'luxury-car', 'autopilot'],
    sellerId: 'seed-seller-3',
    sellerName: 'Premium Auto Sales',
  },
  {
    title: 'Porsche 911 Turbo S',
    description: '2023 Porsche 911 Turbo S. 640 HP, PDK transmission. Only 5,000 miles.',
    category: 'automotive',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600'],
    priceInCoins: 110.0,
    priceInUSD: 220000,
    condition: 'LIKE_NEW',
    quantity: 1,
    location: 'Stuttgart, Germany',
    tags: ['porsche', '911', 'sports-car', 'luxury'],
    sellerId: 'seed-seller-3',
    sellerName: 'Premium Auto Sales',
  },
  {
    title: 'BMW M4 Competition',
    description: '2024 BMW M4 Competition. 503 HP twin-turbo inline-6. Carbon fiber package.',
    category: 'automotive',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600'],
    priceInCoins: 45.0,
    priceInUSD: 90000,
    condition: 'NEW',
    quantity: 2,
    location: 'Munich, Germany',
    tags: ['bmw', 'm4', 'sports-car', 'performance'],
    sellerId: 'seed-seller-3',
    sellerName: 'Premium Auto Sales',
  },
  {
    title: 'Harley-Davidson Street Glide',
    description: '2023 Harley-Davidson Street Glide Special. Milwaukee-Eight 114 engine. Custom paint.',
    category: 'automotive',
    images: ['https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=600'],
    priceInCoins: 15.0,
    priceInUSD: 30000,
    condition: 'LIKE_NEW',
    quantity: 1,
    location: 'Milwaukee, USA',
    tags: ['harley', 'motorcycle', 'cruiser', 'touring'],
    sellerId: 'seed-seller-3',
    sellerName: 'Premium Auto Sales',
  },

  // Real Estate
  {
    title: 'Beachfront Villa in Bali',
    description: 'Luxurious beachfront villa with 5 bedrooms, infinity pool, and ocean views.',
    category: 'real-estate',
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600'],
    priceInCoins: 250.0,
    priceInUSD: 500000,
    condition: 'NEW',
    quantity: 1,
    location: 'Bali, Indonesia',
    tags: ['villa', 'beachfront', 'luxury', 'investment'],
    sellerId: 'seed-seller-4',
    sellerName: 'Tropical Real Estate',
  },
  {
    title: 'Manhattan Penthouse',
    description: 'Stunning penthouse in Manhattan with 360° city views. 4 bed, 4 bath, 3500 sqft.',
    category: 'real-estate',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600'],
    priceInCoins: 2500.0,
    priceInUSD: 5000000,
    condition: 'LIKE_NEW',
    quantity: 1,
    location: 'New York, USA',
    tags: ['penthouse', 'manhattan', 'luxury', 'city-view'],
    sellerId: 'seed-seller-4',
    sellerName: 'Tropical Real Estate',
  },
  {
    title: 'Swiss Chalet in Alps',
    description: 'Traditional Swiss chalet with modern amenities. Ski-in/ski-out access. 6 bedrooms.',
    category: 'real-estate',
    images: ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=600'],
    priceInCoins: 1500.0,
    priceInUSD: 3000000,
    condition: 'GOOD',
    quantity: 1,
    location: 'Zermatt, Switzerland',
    tags: ['chalet', 'ski', 'alps', 'mountain'],
    sellerId: 'seed-seller-4',
    sellerName: 'Tropical Real Estate',
  },

  // Fashion
  {
    title: 'Hermès Birkin Bag',
    description: 'Authentic Hermès Birkin 30cm in Togo leather. Rare color with gold hardware.',
    category: 'fashion',
    images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600'],
    priceInCoins: 12.0,
    priceInUSD: 24000,
    condition: 'NEW',
    quantity: 1,
    location: 'Paris, France',
    tags: ['hermes', 'birkin', 'luxury', 'handbag'],
    sellerId: 'seed-seller-5',
    sellerName: 'Luxury Fashion',
  },
  {
    title: 'Louis Vuitton Trunk',
    description: 'Vintage Louis Vuitton steamer trunk from 1920s. Fully restored, authenticated.',
    category: 'fashion',
    images: ['https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600'],
    priceInCoins: 8.5,
    priceInUSD: 17000,
    condition: 'GOOD',
    quantity: 1,
    location: 'Paris, France',
    tags: ['louis-vuitton', 'vintage', 'trunk', 'collectible'],
    sellerId: 'seed-seller-5',
    sellerName: 'Luxury Fashion',
  },
  {
    title: 'Gucci Leather Jacket',
    description: 'Gucci black leather biker jacket. Made in Italy. Size M.',
    category: 'fashion',
    images: ['https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600'],
    priceInCoins: 1.8,
    priceInUSD: 3600,
    condition: 'NEW',
    quantity: 3,
    location: 'Milan, Italy',
    tags: ['gucci', 'leather', 'jacket', 'designer'],
    sellerId: 'seed-seller-5',
    sellerName: 'Luxury Fashion',
  },
  {
    title: 'Christian Louboutin Heels',
    description: 'Iconic red sole pumps in patent leather. Size 38 EU. Never worn.',
    category: 'fashion',
    images: ['https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600'],
    priceInCoins: 0.65,
    priceInUSD: 1295,
    condition: 'NEW',
    quantity: 2,
    location: 'Paris, France',
    tags: ['louboutin', 'heels', 'shoes', 'designer'],
    sellerId: 'seed-seller-5',
    sellerName: 'Luxury Fashion',
  },

  // Collectibles & Art
  {
    title: 'Limited Edition NFT Art Print',
    description: 'Physical print of popular NFT artwork. Signed by the artist. Only 100 editions available.',
    category: 'collectibles-art',
    images: ['https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=600'],
    priceInCoins: 2.5,
    priceInUSD: 5000,
    condition: 'NEW',
    quantity: 5,
    location: 'Los Angeles, USA',
    tags: ['nft', 'art', 'limited-edition', 'crypto-art'],
    sellerId: 'seed-seller-6',
    sellerName: 'CryptoArt Gallery',
  },
  {
    title: 'Picasso Original Sketch',
    description: 'Original pencil sketch by Pablo Picasso from 1950s. Authenticated by expert.',
    category: 'collectibles-art',
    images: ['https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=600'],
    priceInCoins: 150.0,
    priceInUSD: 300000,
    condition: 'GOOD',
    quantity: 1,
    location: 'Barcelona, Spain',
    tags: ['picasso', 'art', 'original', 'sketch'],
    sellerId: 'seed-seller-6',
    sellerName: 'CryptoArt Gallery',
  },
  {
    title: 'Rare Pokemon Card Collection',
    description: 'Complete first edition base set. All cards graded PSA 9 or higher.',
    category: 'collectibles-art',
    images: ['https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=600'],
    priceInCoins: 25.0,
    priceInUSD: 50000,
    condition: 'LIKE_NEW',
    quantity: 1,
    location: 'Tokyo, Japan',
    tags: ['pokemon', 'cards', 'collectible', 'graded'],
    sellerId: 'seed-seller-6',
    sellerName: 'CryptoArt Gallery',
  },
  {
    title: 'Banksy Print "Girl with Balloon"',
    description: 'Signed and numbered Banksy print. Limited edition of 500.',
    category: 'collectibles-art',
    images: ['https://images.unsplash.com/photo-1578926078716-c5f06c0c2e4e?w=600'],
    priceInCoins: 18.0,
    priceInUSD: 36000,
    condition: 'NEW',
    quantity: 1,
    location: 'London, UK',
    tags: ['banksy', 'print', 'street-art', 'limited'],
    sellerId: 'seed-seller-6',
    sellerName: 'CryptoArt Gallery',
  },

  // Sports & Outdoors
  {
    title: 'Specialized S-Works Bike',
    description: 'Professional road bike with carbon frame. Shimano Dura-Ace groupset.',
    category: 'sports-outdoors',
    images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=600'],
    priceInCoins: 0.65,
    priceInUSD: 13000,
    condition: 'NEW',
    quantity: 2,
    location: 'California, USA',
    tags: ['bike', 'cycling', 'carbon', 'professional'],
    sellerId: 'seed-seller-7',
    sellerName: 'Sports Equipment Pro',
  },
  {
    title: 'Titleist Golf Club Set',
    description: 'Complete Titleist golf club set with bag. Professional grade.',
    category: 'sports-outdoors',
    images: ['https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=600'],
    priceInCoins: 0.15,
    priceInUSD: 3000,
    condition: 'NEW',
    quantity: 5,
    location: 'Florida, USA',
    tags: ['golf', 'titleist', 'clubs', 'professional'],
    sellerId: 'seed-seller-7',
    sellerName: 'Sports Equipment Pro',
  },
  {
    title: 'Rossignol Ski Package',
    description: 'Premium ski package with boots and bindings. Size 180cm.',
    category: 'sports-outdoors',
    images: ['https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600'],
    priceInCoins: 0.08,
    priceInUSD: 1600,
    condition: 'NEW',
    quantity: 4,
    location: 'Chamonix, France',
    tags: ['ski', 'winter', 'rossignol', 'alpine'],
    sellerId: 'seed-seller-7',
    sellerName: 'Sports Equipment Pro',
  },
  {
    title: 'Peloton Bike+',
    description: 'Peloton Bike+ with rotating screen and auto-resistance. Includes 1-year membership.',
    category: 'sports-outdoors',
    images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600'],
    priceInCoins: 0.125,
    priceInUSD: 2495,
    condition: 'NEW',
    quantity: 10,
    location: 'New York, USA',
    tags: ['peloton', 'fitness', 'bike', 'home-gym'],
    sellerId: 'seed-seller-7',
    sellerName: 'Sports Equipment Pro',
  },

  // Home & Garden
  {
    title: 'Herman Miller Eames Lounge Chair',
    description: 'Authentic Eames lounge chair and ottoman in black leather.',
    category: 'home-garden',
    images: ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600'],
    priceInCoins: 0.35,
    priceInUSD: 7000,
    condition: 'NEW',
    quantity: 3,
    location: 'Michigan, USA',
    tags: ['eames', 'chair', 'designer', 'furniture'],
    sellerId: 'seed-seller-8',
    sellerName: 'Designer Furniture',
  },
  {
    title: 'Bang & Olufsen Beosound Theatre',
    description: 'Premium soundbar with Dolby Atmos. Handcrafted aluminum design.',
    category: 'home-garden',
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=600'],
    priceInCoins: 0.45,
    priceInUSD: 9000,
    condition: 'NEW',
    quantity: 5,
    location: 'Copenhagen, Denmark',
    tags: ['audio', 'soundbar', 'luxury', 'design'],
    sellerId: 'seed-seller-8',
    sellerName: 'Designer Furniture',
  },
  {
    title: 'La Marzocco Espresso Machine',
    description: 'Professional espresso machine. Dual boiler system. Barista quality.',
    category: 'home-garden',
    images: ['https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600'],
    priceInCoins: 0.45,
    priceInUSD: 9000,
    condition: 'NEW',
    quantity: 2,
    location: 'Florence, Italy',
    tags: ['espresso', 'coffee', 'professional', 'italian'],
    sellerId: 'seed-seller-8',
    sellerName: 'Designer Furniture',
  },
  {
    title: 'Dyson Airwrap Complete',
    description: 'Complete Dyson Airwrap styling set with all attachments. Long barrel version.',
    category: 'home-garden',
    images: ['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600'],
    priceInCoins: 0.03,
    priceInUSD: 599,
    condition: 'NEW',
    quantity: 20,
    location: 'Singapore',
    tags: ['dyson', 'hair', 'styling', 'beauty'],
    sellerId: 'seed-seller-8',
    sellerName: 'Designer Furniture',
  },

  // Additional Premium Items
  {
    title: 'Rolex Daytona Platinum',
    description: 'Rolex Cosmograph Daytona in platinum with ice blue dial. Extremely rare.',
    category: 'jewelry-watches',
    images: ['https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600'],
    priceInCoins: 75.0,
    priceInUSD: 150000,
    condition: 'NEW',
    quantity: 1,
    location: 'Geneva, Switzerland',
    tags: ['rolex', 'daytona', 'platinum', 'rare'],
    sellerId: 'seed-seller-1',
    sellerName: 'Luxury Timepieces',
  },
  {
    title: 'Patek Philippe Nautilus',
    description: 'Patek Philippe Nautilus 5711 in stainless steel. Blue dial. Full set.',
    category: 'jewelry-watches',
    images: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600'],
    priceInCoins: 85.0,
    priceInUSD: 170000,
    condition: 'LIKE_NEW',
    quantity: 1,
    location: 'Geneva, Switzerland',
    tags: ['patek', 'nautilus', 'luxury', 'investment'],
    sellerId: 'seed-seller-1',
    sellerName: 'Luxury Timepieces',
  },
  {
    title: 'Audemars Piguet Royal Oak',
    description: 'AP Royal Oak 41mm in rose gold. Black dial with Grande Tapisserie pattern.',
    category: 'jewelry-watches',
    images: ['https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=600'],
    priceInCoins: 55.0,
    priceInUSD: 110000,
    condition: 'NEW',
    quantity: 1,
    location: 'Le Brassus, Switzerland',
    tags: ['audemars', 'royal-oak', 'luxury', 'gold'],
    sellerId: 'seed-seller-1',
    sellerName: 'Luxury Timepieces',
  },
  {
    title: 'Lamborghini Huracán EVO',
    description: '2023 Lamborghini Huracán EVO. 640 HP V10 engine. Only 2,000 miles.',
    category: 'automotive',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=600'],
    priceInCoins: 150.0,
    priceInUSD: 300000,
    condition: 'LIKE_NEW',
    quantity: 1,
    location: 'Sant\'Agata, Italy',
    tags: ['lamborghini', 'supercar', 'v10', 'exotic'],
    sellerId: 'seed-seller-3',
    sellerName: 'Premium Auto Sales',
  },
  {
    title: 'Ferrari F8 Tributo',
    description: '2024 Ferrari F8 Tributo. Rosso Corsa red. Carbon fiber package.',
    category: 'automotive',
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600'],
    priceInCoins: 175.0,
    priceInUSD: 350000,
    condition: 'NEW',
    quantity: 1,
    location: 'Maranello, Italy',
    tags: ['ferrari', 'supercar', 'italian', 'exotic'],
    sellerId: 'seed-seller-3',
    sellerName: 'Premium Auto Sales',
  },
  {
    title: 'McLaren 720S Spider',
    description: '2023 McLaren 720S Spider. MSO options. Carbon fiber everywhere.',
    category: 'automotive',
    images: ['https://images.unsplash.com/photo-1563720360172-67b8f3dce741?w=600'],
    priceInCoins: 165.0,
    priceInUSD: 330000,
    condition: 'LIKE_NEW',
    quantity: 1,
    location: 'Woking, UK',
    tags: ['mclaren', 'supercar', 'spider', 'carbon'],
    sellerId: 'seed-seller-3',
    sellerName: 'Premium Auto Sales',
  },
  {
    title: 'Chanel Classic Flap Bag',
    description: 'Chanel Classic Medium Flap in caviar leather. Gold hardware. Timeless piece.',
    category: 'fashion',
    images: ['https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600'],
    priceInCoins: 4.5,
    priceInUSD: 9000,
    condition: 'NEW',
    quantity: 2,
    location: 'Paris, France',
    tags: ['chanel', 'handbag', 'classic', 'luxury'],
    sellerId: 'seed-seller-5',
    sellerName: 'Luxury Fashion',
  },
  {
    title: 'Dior Book Tote',
    description: 'Dior Book Tote in embroidered canvas. Limited edition pattern.',
    category: 'fashion',
    images: ['https://images.unsplash.com/photo-1591561954557-26941169b49e?w=600'],
    priceInCoins: 1.8,
    priceInUSD: 3600,
    condition: 'NEW',
    quantity: 3,
    location: 'Paris, France',
    tags: ['dior', 'tote', 'designer', 'limited'],
    sellerId: 'seed-seller-5',
    sellerName: 'Luxury Fashion',
  },
  {
    title: 'Rolex GMT-Master II',
    description: 'Rolex GMT-Master II "Pepsi" with Jubilee bracelet. Ceramic bezel.',
    category: 'jewelry-watches',
    images: ['https://images.unsplash.com/photo-1622434641406-a158123450f9?w=600'],
    priceInCoins: 18.0,
    priceInUSD: 36000,
    condition: 'NEW',
    quantity: 1,
    location: 'Geneva, Switzerland',
    tags: ['rolex', 'gmt', 'pepsi', 'travel'],
    sellerId: 'seed-seller-1',
    sellerName: 'Luxury Timepieces',
  },
  {
    title: 'Omega Speedmaster Moonwatch',
    description: 'Omega Speedmaster Professional Moonwatch. Hesalite crystal. Manual wind.',
    category: 'jewelry-watches',
    images: ['https://images.unsplash.com/photo-1611003228941-98852ba62227?w=600'],
    priceInCoins: 3.2,
    priceInUSD: 6400,
    condition: 'NEW',
    quantity: 5,
    location: 'Biel, Switzerland',
    tags: ['omega', 'speedmaster', 'moonwatch', 'space'],
    sellerId: 'seed-seller-1',
    sellerName: 'Luxury Timepieces',
  },
  {
    title: 'Sony PlayStation 5 Pro',
    description: 'Latest PS5 Pro console with 2TB SSD. Includes DualSense Edge controller.',
    category: 'electronics',
    images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600'],
    priceInCoins: 0.035,
    priceInUSD: 699,
    condition: 'NEW',
    quantity: 25,
    location: 'Tokyo, Japan',
    tags: ['playstation', 'gaming', 'console', 'ps5'],
    sellerId: 'seed-seller-2',
    sellerName: 'Tech Store',
  },
  {
    title: 'DJI Mavic 3 Pro Drone',
    description: 'Professional drone with triple camera system. 4/3 CMOS Hasselblad camera.',
    category: 'electronics',
    images: ['https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600'],
    priceInCoins: 0.11,
    priceInUSD: 2199,
    condition: 'NEW',
    quantity: 8,
    location: 'Shenzhen, China',
    tags: ['drone', 'dji', 'camera', 'aerial'],
    sellerId: 'seed-seller-2',
    sellerName: 'Tech Store',
  },
  {
    title: 'Bose QuietComfort Ultra',
    description: 'Premium noise-cancelling headphones. Spatial audio support.',
    category: 'electronics',
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600'],
    priceInCoins: 0.021,
    priceInUSD: 429,
    condition: 'NEW',
    quantity: 30,
    location: 'Massachusetts, USA',
    tags: ['headphones', 'bose', 'noise-cancelling', 'audio'],
    sellerId: 'seed-seller-2',
    sellerName: 'Tech Store',
  },
  {
    title: 'Leica Q3 Camera',
    description: 'Leica Q3 with 60MP full-frame sensor and 28mm f/1.7 lens.',
    category: 'electronics',
    images: ['https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600'],
    priceInCoins: 0.3,
    priceInUSD: 6000,
    condition: 'NEW',
    quantity: 3,
    location: 'Wetzlar, Germany',
    tags: ['leica', 'camera', 'luxury', 'photography'],
    sellerId: 'seed-seller-2',
    sellerName: 'Tech Store',
  },
  {
    title: 'Steinway Model D Grand Piano',
    description: 'Concert grand piano. 9 feet. Handcrafted in New York.',
    category: 'collectibles-art',
    images: ['https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600'],
    priceInCoins: 90.0,
    priceInUSD: 180000,
    condition: 'NEW',
    quantity: 1,
    location: 'New York, USA',
    tags: ['piano', 'steinway', 'music', 'concert'],
    sellerId: 'seed-seller-6',
    sellerName: 'CryptoArt Gallery',
  },
];

// Auto-assign coin data based on price range
const assignCoinData = (priceInUSD: number) => {
  if (priceInUSD >= 10000) {
    // High-value items: BTC
    return {
      coinSymbol: 'BTC',
      coinLogo: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
      priceInCoins: parseFloat((priceInUSD / 43000).toFixed(4)),
    };
  } else if (priceInUSD >= 1000) {
    // Mid-high value: ETH
    return {
      coinSymbol: 'ETH',
      coinLogo: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
      priceInCoins: parseFloat((priceInUSD / 2300).toFixed(4)),
    };
  } else if (priceInUSD >= 300) {
    // Mid value: BNB
    return {
      coinSymbol: 'BNB',
      coinLogo: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png',
      priceInCoins: parseFloat((priceInUSD / 320).toFixed(4)),
    };
  } else if (priceInUSD >= 50) {
    // Low-mid value: XRP
    return {
      coinSymbol: 'XRP',
      coinLogo: 'https://assets.coingecko.com/coins/images/44/small/xrp-symbol-white-128.png',
      priceInCoins: parseFloat((priceInUSD / 0.52).toFixed(2)),
    };
  } else {
    // Low value: USDT (stablecoin)
    return {
      coinSymbol: 'USDT',
      coinLogo: 'https://assets.coingecko.com/coins/images/325/small/Tether.png',
      priceInCoins: priceInUSD,
    };
  }
};

// Process products and assign coin data
const sampleProducts = realWorldProducts.map((product, index) => {
  // If product already has coinSymbol, use it
  if (product.coinSymbol) {
    return product;
  }
  
  // Otherwise, auto-assign based on price
  const coinInfo = assignCoinData(product.priceInUSD);
  
  // Fixed reviews based on index to avoid random
  const fixedReviews = [
    150, 89, 234, 45, 178, 92, 305, 67, 128, 213,
    156, 98, 267, 134, 189, 76, 245, 112, 198, 87,
    223, 145, 167, 91, 256, 103, 189, 78, 201, 134,
    178, 95, 234, 109, 167, 88, 212, 125, 189, 102,
    256, 118, 195, 84, 231, 107, 174, 93, 209, 121
  ];
  
  return {
    ...product,
    ...coinInfo,
    rating: product.rating || 4.5,
    reviews: product.reviews || fixedReviews[index % fixedReviews.length],
  };
});

const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017';
    const dbName = process.env.MONGODB_DB_PRODUCT || 'product_db';
    await mongoose.connect(`${mongoUri}/${dbName}`);

    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Product.deleteMany({});
    await Category.deleteMany({});
    console.log('✅ Cleared existing data');

    // Seed categories
    await Category.insertMany(categories);
    console.log(`✅ Seeded ${categories.length} categories`);

    // Seed products
    await Product.insertMany(sampleProducts);
    console.log(`✅ Seeded ${sampleProducts.length} products`);

    console.log('✅ Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
};

seedDatabase();

