/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RWAMarketEscrow {
  export type ListingStruct = {
    id: BigNumberish;
    seller: AddressLike;
    tokenAddress: AddressLike;
    tokenAmount: BigNumberish;
    pricePerTokenWei: BigNumberish;
    active: boolean;
    createdAt: BigNumberish;
  };

  export type ListingStructOutput = [
    id: bigint,
    seller: string,
    tokenAddress: string,
    tokenAmount: bigint,
    pricePerTokenWei: bigint,
    active: boolean,
    createdAt: bigint
  ] & {
    id: bigint;
    seller: string;
    tokenAddress: string;
    tokenAmount: bigint;
    pricePerTokenWei: bigint;
    active: boolean;
    createdAt: bigint;
  };
}

export interface RWAMarketEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyListing"
      | "cancelListing"
      | "compliance"
      | "getActiveListing"
      | "listTokens"
      | "listingCount"
      | "listings"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Cancelled" | "Listed" | "Sold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "compliance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listTokens",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listingCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "compliance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
}

export namespace CancelledEvent {
  export type InputTuple = [listingId: BigNumberish];
  export type OutputTuple = [listingId: bigint];
  export interface OutputObject {
    listingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ListedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    seller: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    pricePerToken: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    seller: string,
    token: string,
    amount: bigint,
    pricePerToken: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
    token: string;
    amount: bigint;
    pricePerToken: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SoldEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    buyer: AddressLike,
    amount: BigNumberish,
    totalPriceWei: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    buyer: string,
    amount: bigint,
    totalPriceWei: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    buyer: string;
    amount: bigint;
    totalPriceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RWAMarketEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): RWAMarketEscrow;
  waitForDeployment(): Promise<this>;

  interface: RWAMarketEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyListing: TypedContractMethod<[listingId: BigNumberish], [void], "payable">;

  cancelListing: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  compliance: TypedContractMethod<[], [string], "view">;

  getActiveListing: TypedContractMethod<
    [listingId: BigNumberish],
    [RWAMarketEscrow.ListingStructOutput],
    "view"
  >;

  listTokens: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      amount: BigNumberish,
      pricePerTokenWei: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  listingCount: TypedContractMethod<[], [bigint], "view">;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint] & {
        id: bigint;
        seller: string;
        tokenAddress: string;
        tokenAmount: bigint;
        pricePerTokenWei: bigint;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyListing"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "compliance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveListing"
  ): TypedContractMethod<
    [listingId: BigNumberish],
    [RWAMarketEscrow.ListingStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "listTokens"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      amount: BigNumberish,
      pricePerTokenWei: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listingCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean, bigint] & {
        id: bigint;
        seller: string;
        tokenAddress: string;
        tokenAmount: bigint;
        pricePerTokenWei: bigint;
        active: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "Cancelled"
  ): TypedContractEvent<
    CancelledEvent.InputTuple,
    CancelledEvent.OutputTuple,
    CancelledEvent.OutputObject
  >;
  getEvent(
    key: "Listed"
  ): TypedContractEvent<
    ListedEvent.InputTuple,
    ListedEvent.OutputTuple,
    ListedEvent.OutputObject
  >;
  getEvent(
    key: "Sold"
  ): TypedContractEvent<
    SoldEvent.InputTuple,
    SoldEvent.OutputTuple,
    SoldEvent.OutputObject
  >;

  filters: {
    "Cancelled(uint256)": TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;
    Cancelled: TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;

    "Listed(uint256,address,address,uint256,uint256)": TypedContractEvent<
      ListedEvent.InputTuple,
      ListedEvent.OutputTuple,
      ListedEvent.OutputObject
    >;
    Listed: TypedContractEvent<
      ListedEvent.InputTuple,
      ListedEvent.OutputTuple,
      ListedEvent.OutputObject
    >;

    "Sold(uint256,address,uint256,uint256)": TypedContractEvent<
      SoldEvent.InputTuple,
      SoldEvent.OutputTuple,
      SoldEvent.OutputObject
    >;
    Sold: TypedContractEvent<
      SoldEvent.InputTuple,
      SoldEvent.OutputTuple,
      SoldEvent.OutputObject
    >;
  };
}
