ALTER TABLE orders ADD COLUMN IF NOT EXISTS pricing_mode VARCHAR(20) DEFAULT 'usd';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS product_token_id INT REFERENCES token_whitelist(token_id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS price_token DECIMAL(36,18);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_token DECIMAL(36,18);
