/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProfitDistributorV2,
  IProfitDistributorV2Interface,
} from "../../../contracts/RWATokenV2.sol/IProfitDistributorV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "settleOnTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IProfitDistributorV2__factory {
  static readonly abi = _abi;
  static createInterface(): IProfitDistributorV2Interface {
    return new Interface(_abi) as IProfitDistributorV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProfitDistributorV2 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IProfitDistributorV2;
  }
}
