/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace EscrowCore {
  export type OrderStruct = {
    buyer: AddressLike;
    seller: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    fee: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
  };

  export type OrderStructOutput = [
    buyer: string,
    seller: string,
    token: string,
    amount: bigint,
    fee: bigint,
    status: bigint,
    createdAt: bigint,
    expiresAt: bigint
  ] & {
    buyer: string;
    seller: string;
    token: string;
    amount: bigint;
    fee: bigint;
    status: bigint;
    createdAt: bigint;
    expiresAt: bigint;
  };
}

export interface EscrowCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_FEE_PERCENT"
      | "OPERATOR_ROLE"
      | "ORDER_TIMEOUT"
      | "buyerConfirmDelivery"
      | "deposit"
      | "depositBatch"
      | "depositNative"
      | "depositNativeBatch"
      | "depositWithSwap"
      | "feeVault"
      | "getEffectiveFee"
      | "getOrder"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "orders"
      | "pause"
      | "paused"
      | "platformFeePercent"
      | "raiseDispute"
      | "refund"
      | "refundExpired"
      | "releasePayment"
      | "renounceRole"
      | "revokeRole"
      | "sbtContract"
      | "setSBTContract"
      | "supportsInterface"
      | "unpause"
      | "updateFeeVault"
      | "updatePlatformFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeliveryConfirmed"
      | "FeeUpdated"
      | "FeeVaultUpdated"
      | "OrderCompleted"
      | "OrderCreated"
      | "OrderDisputed"
      | "OrderExpired"
      | "OrderRefunded"
      | "Paused"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SBTContractUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORDER_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyerConfirmDelivery",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositBatch",
    values: [BytesLike[], AddressLike, BigNumberish[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNative",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNativeBatch",
    values: [BytesLike[], AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWithSwap",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "feeVault", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getEffectiveFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getOrder", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "orders", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "refund", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "refundExpired",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releasePayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sbtContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSBTContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateFeeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformFee",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORDER_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyerConfirmDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositNativeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositWithSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEffectiveFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releasePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sbtContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSBTContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateFeeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformFee",
    data: BytesLike
  ): Result;
}

export namespace DeliveryConfirmedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    buyer: AddressLike,
    seller: AddressLike,
    onTime: boolean
  ];
  export type OutputTuple = [
    orderId: string,
    buyer: string,
    seller: string,
    onTime: boolean
  ];
  export interface OutputObject {
    orderId: string;
    buyer: string;
    seller: string;
    onTime: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeVaultUpdatedEvent {
  export type InputTuple = [newVault: AddressLike];
  export type OutputTuple = [newVault: string];
  export interface OutputObject {
    newVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCompletedEvent {
  export type InputTuple = [orderId: BytesLike];
  export type OutputTuple = [orderId: string];
  export interface OutputObject {
    orderId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    buyer: AddressLike,
    seller: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    buyer: string,
    seller: string,
    token: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    orderId: string;
    buyer: string;
    seller: string;
    token: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderDisputedEvent {
  export type InputTuple = [orderId: BytesLike];
  export type OutputTuple = [orderId: string];
  export interface OutputObject {
    orderId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderExpiredEvent {
  export type InputTuple = [orderId: BytesLike];
  export type OutputTuple = [orderId: string];
  export interface OutputObject {
    orderId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderRefundedEvent {
  export type InputTuple = [orderId: BytesLike];
  export type OutputTuple = [orderId: string];
  export interface OutputObject {
    orderId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SBTContractUpdatedEvent {
  export type InputTuple = [newSBT: AddressLike];
  export type OutputTuple = [newSBT: string];
  export interface OutputObject {
    newSBT: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EscrowCore extends BaseContract {
  connect(runner?: ContractRunner | null): EscrowCore;
  waitForDeployment(): Promise<this>;

  interface: EscrowCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  ORDER_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  buyerConfirmDelivery: TypedContractMethod<
    [orderId: BytesLike],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [
      orderId: BytesLike,
      token: AddressLike,
      amount: BigNumberish,
      seller: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  depositBatch: TypedContractMethod<
    [
      orderIds: BytesLike[],
      token: AddressLike,
      amounts: BigNumberish[],
      sellers: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  depositNative: TypedContractMethod<
    [orderId: BytesLike, seller: AddressLike],
    [void],
    "payable"
  >;

  depositNativeBatch: TypedContractMethod<
    [orderIds: BytesLike[], sellers: AddressLike[], amounts: BigNumberish[]],
    [void],
    "payable"
  >;

  depositWithSwap: TypedContractMethod<
    [
      orderId: BytesLike,
      inputToken: AddressLike,
      requiredToken: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      seller: AddressLike,
      routerAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  feeVault: TypedContractMethod<[], [string], "view">;

  getEffectiveFee: TypedContractMethod<[buyer: AddressLike], [bigint], "view">;

  getOrder: TypedContractMethod<
    [orderId: BytesLike],
    [EscrowCore.OrderStructOutput],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  orders: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        token: string;
        amount: bigint;
        fee: bigint;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  raiseDispute: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  refund: TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;

  refundExpired: TypedContractMethod<
    [orderId: BytesLike],
    [void],
    "nonpayable"
  >;

  releasePayment: TypedContractMethod<
    [orderId: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  sbtContract: TypedContractMethod<[], [string], "view">;

  setSBTContract: TypedContractMethod<
    [_sbt: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateFeeVault: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlatformFee: TypedContractMethod<
    [newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ORDER_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyerConfirmDelivery"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      token: AddressLike,
      amount: BigNumberish,
      seller: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositBatch"
  ): TypedContractMethod<
    [
      orderIds: BytesLike[],
      token: AddressLike,
      amounts: BigNumberish[],
      sellers: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositNative"
  ): TypedContractMethod<
    [orderId: BytesLike, seller: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositNativeBatch"
  ): TypedContractMethod<
    [orderIds: BytesLike[], sellers: AddressLike[], amounts: BigNumberish[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "depositWithSwap"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      inputToken: AddressLike,
      requiredToken: AddressLike,
      amountIn: BigNumberish,
      minAmountOut: BigNumberish,
      seller: AddressLike,
      routerAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEffectiveFee"
  ): TypedContractMethod<[buyer: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [EscrowCore.OrderStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, bigint, bigint] & {
        buyer: string;
        seller: string;
        token: string;
        amount: bigint;
        fee: bigint;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "refundExpired"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "releasePayment"
  ): TypedContractMethod<[orderId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sbtContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSBTContract"
  ): TypedContractMethod<[_sbt: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFeeVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlatformFee"
  ): TypedContractMethod<[newFeePercent: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DeliveryConfirmed"
  ): TypedContractEvent<
    DeliveryConfirmedEvent.InputTuple,
    DeliveryConfirmedEvent.OutputTuple,
    DeliveryConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "FeeUpdated"
  ): TypedContractEvent<
    FeeUpdatedEvent.InputTuple,
    FeeUpdatedEvent.OutputTuple,
    FeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeVaultUpdated"
  ): TypedContractEvent<
    FeeVaultUpdatedEvent.InputTuple,
    FeeVaultUpdatedEvent.OutputTuple,
    FeeVaultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCompleted"
  ): TypedContractEvent<
    OrderCompletedEvent.InputTuple,
    OrderCompletedEvent.OutputTuple,
    OrderCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderDisputed"
  ): TypedContractEvent<
    OrderDisputedEvent.InputTuple,
    OrderDisputedEvent.OutputTuple,
    OrderDisputedEvent.OutputObject
  >;
  getEvent(
    key: "OrderExpired"
  ): TypedContractEvent<
    OrderExpiredEvent.InputTuple,
    OrderExpiredEvent.OutputTuple,
    OrderExpiredEvent.OutputObject
  >;
  getEvent(
    key: "OrderRefunded"
  ): TypedContractEvent<
    OrderRefundedEvent.InputTuple,
    OrderRefundedEvent.OutputTuple,
    OrderRefundedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SBTContractUpdated"
  ): TypedContractEvent<
    SBTContractUpdatedEvent.InputTuple,
    SBTContractUpdatedEvent.OutputTuple,
    SBTContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "DeliveryConfirmed(bytes32,address,address,bool)": TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;
    DeliveryConfirmed: TypedContractEvent<
      DeliveryConfirmedEvent.InputTuple,
      DeliveryConfirmedEvent.OutputTuple,
      DeliveryConfirmedEvent.OutputObject
    >;

    "FeeUpdated(uint256)": TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;
    FeeUpdated: TypedContractEvent<
      FeeUpdatedEvent.InputTuple,
      FeeUpdatedEvent.OutputTuple,
      FeeUpdatedEvent.OutputObject
    >;

    "FeeVaultUpdated(address)": TypedContractEvent<
      FeeVaultUpdatedEvent.InputTuple,
      FeeVaultUpdatedEvent.OutputTuple,
      FeeVaultUpdatedEvent.OutputObject
    >;
    FeeVaultUpdated: TypedContractEvent<
      FeeVaultUpdatedEvent.InputTuple,
      FeeVaultUpdatedEvent.OutputTuple,
      FeeVaultUpdatedEvent.OutputObject
    >;

    "OrderCompleted(bytes32)": TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;
    OrderCompleted: TypedContractEvent<
      OrderCompletedEvent.InputTuple,
      OrderCompletedEvent.OutputTuple,
      OrderCompletedEvent.OutputObject
    >;

    "OrderCreated(bytes32,address,address,address,uint256,uint256)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderDisputed(bytes32)": TypedContractEvent<
      OrderDisputedEvent.InputTuple,
      OrderDisputedEvent.OutputTuple,
      OrderDisputedEvent.OutputObject
    >;
    OrderDisputed: TypedContractEvent<
      OrderDisputedEvent.InputTuple,
      OrderDisputedEvent.OutputTuple,
      OrderDisputedEvent.OutputObject
    >;

    "OrderExpired(bytes32)": TypedContractEvent<
      OrderExpiredEvent.InputTuple,
      OrderExpiredEvent.OutputTuple,
      OrderExpiredEvent.OutputObject
    >;
    OrderExpired: TypedContractEvent<
      OrderExpiredEvent.InputTuple,
      OrderExpiredEvent.OutputTuple,
      OrderExpiredEvent.OutputObject
    >;

    "OrderRefunded(bytes32)": TypedContractEvent<
      OrderRefundedEvent.InputTuple,
      OrderRefundedEvent.OutputTuple,
      OrderRefundedEvent.OutputObject
    >;
    OrderRefunded: TypedContractEvent<
      OrderRefundedEvent.InputTuple,
      OrderRefundedEvent.OutputTuple,
      OrderRefundedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SBTContractUpdated(address)": TypedContractEvent<
      SBTContractUpdatedEvent.InputTuple,
      SBTContractUpdatedEvent.OutputTuple,
      SBTContractUpdatedEvent.OutputObject
    >;
    SBTContractUpdated: TypedContractEvent<
      SBTContractUpdatedEvent.InputTuple,
      SBTContractUpdatedEvent.OutputTuple,
      SBTContractUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
