/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICreditScoreSBTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getPlatformFee"
      | "getTier"
      | "recordCompletedOrder"
      | "recordDispute"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPlatformFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCompletedOrder",
    values: [AddressLike, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDispute",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordCompletedOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDispute",
    data: BytesLike
  ): Result;
}

export interface ICreditScoreSBT extends BaseContract {
  connect(runner?: ContractRunner | null): ICreditScoreSBT;
  waitForDeployment(): Promise<this>;

  interface: ICreditScoreSBTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getPlatformFee: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  getTier: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  recordCompletedOrder: TypedContractMethod<
    [wallet: AddressLike, onTime: boolean, reason: string],
    [void],
    "nonpayable"
  >;

  recordDispute: TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getPlatformFee"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTier"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordCompletedOrder"
  ): TypedContractMethod<
    [wallet: AddressLike, onTime: boolean, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordDispute"
  ): TypedContractMethod<
    [wallet: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
