/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGovernanceRWA,
  IGovernanceRWAInterface,
} from "../../../contracts/BuyoutVault.sol/IGovernanceRWA";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "expectedHash",
        type: "bytes32",
      },
    ],
    name: "verifyPassedProposal",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGovernanceRWA__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernanceRWAInterface {
    return new Interface(_abi) as IGovernanceRWAInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGovernanceRWA {
    return new Contract(address, _abi, runner) as unknown as IGovernanceRWA;
  }
}
