/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProfitDistributor,
  IProfitDistributorInterface,
} from "../../../contracts/RWAToken.sol/IProfitDistributor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "settleOnTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IProfitDistributor__factory {
  static readonly abi = _abi;
  static createInterface(): IProfitDistributorInterface {
    return new Interface(_abi) as IProfitDistributorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProfitDistributor {
    return new Contract(address, _abi, runner) as unknown as IProfitDistributor;
  }
}
