name: Deploy FinalYear Project

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: almalinux-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/services/FinalYear

            echo "Pull latest code..."
            git fetch origin
            git checkout production
            git pull origin production

            echo "Go to docker folder..."
            cd docker

            echo "Stop old containers..."
            docker compose down

            echo "Build and start new containers..."
            docker compose up -d --build

            echo "Deployment completed!"